name: pull-request
on:
  push:
jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17  # Choose the Java version you are using
          distribution: oracle

      - name: Build Gradle Project
        run: ./gradlew build -x test

      - name: Run Tests
        run: ./gradlew test  # Then run tests

      - name: Run Checkstyle
        run: |
          # Setting up Checkstyle
          curl -o checkstyle.jar -L https://github.com/checkstyle/checkstyle/releases/download/8.43/checkstyle-8.43-all.jar
          
          # Running Checkstyle
          java -jar checkstyle.jar -c /config/checkstyle/checkstyle.xml src/  # Specify the path to the checkstyle.xml file and the source code directory

        continue-on-error: true  # Continue even if there are errors

      - name: Checkstyle Summary
        run: |
          # Outputs a summary message of the check results
          if [ -f checkstyle-result.xml ]; then
          echo "checkstyle=$(grep -c '<error' checkstyle-result.xml) errors found" >> $GITHUB_ENV
          else
          echo "checkstyle=0 errors found" >> $GITHUB_ENV
          fi